### ISSUE TITLE
Send data to InfluxDB from monitoring daemon

### ISSUE THREAD

**Issue by lsegiet** [akamai-api/golang#10]
- Understanding the input in Kafka
- Sending the output of the daemon directly to Kafka

**Comment by mre** [comment]
As discussed, we won't send data to Kafka but instead send the data to InfluxDB directly.

Advantages:
* Saves time (deadline approaching)
* No dependency on Kafka (and Logstash).

Disadvantages:
* We lose the buffer functionality.

**Comment by lsegiet** [comment]
We send the data to influxDB.
