### ISSUE TITLE
Define Akamai metrics

### ISSUE THREAD

**Issue by mre** [akamai-api/golang#15]
We have a number of sample requests from the Akamai Cloudwatch API.
There are unknown fields in the json request payload.
We need to define the purpose of the properties before we can use them for our monitoring daemon.

**Comment by mre** [comment]
Expected format:

Some text file (maybe markdown format):

For every field in the `JSON` payload, we need an entry like this:

`field_name`: purpose (example)
`field_name`: purpose (example)
`field_name`: purpose (example)
...


JSON file is here:https://github.com/akamai-api/golang/blob/master/tests/payload.json

**Comment by lsegiet** [comment]
Done. AkamaiPayload structure put in the file:
https://github.com/akamai-api/golang/blob/master/Server/server.go
