### ISSUE TITLE
Akamai API Overview

### ISSUE THREAD

**Issue by lsegiet** [akamai-api/golang#2]
- read API documentation
- provide links to the relevant documentation

**Comment by imghasemi** [comment]
The source for digging into AKAMAI
https://developer.akamai.com/api

**Comment by mre** [comment]
https://www.akamai.com/us/en/solutions/intelligent-platform/cloud-monitor.jsp

**Comment by mre** [comment]
https://www.splunk.com/blog/2015/09/18/capturing-akamai-data-with-splunk.html
