### ISSUE TITLE
Switch monitoring backend to Prometheus

### ISSUE THREAD

**Issue by mre** [akamai-api/golang#20]
We recently migrated our monitoring for edgecast and chinacache to microservices exposing data in prometheus format. Read the [article on our techblog](http://tech.trivago.com/2018/01/10/splitting-a-monitoring-monolith-into-separate-components/).
In order to make our infrastructure more homogenous, it would be nice to have the same metric format everywhere. Therefore it would be great, if this service could also expose metrics in prometheus format.

**Comment by iwilltry42** [comment]
Will have to use the Prometheus Pushgateway or expose two endpoints.

**Comment by iwilltry42** [comment]
Functionality already implemented here: [https://github.com/ExpressenAB/cloudmonitor_exporter](https://github.com/ExpressenAB/cloudmonitor_exporter)

**Comment by mre** [comment]
Thanks for the link. I totally forgot about that. Closing. 😊
