### ISSUE TITLE
Learn how to create dashboard for presenting the final product

### ISSUE THREAD

**Issue by imghasemi** [akamai-api/golang#9]

**Comment by mre** [comment]
![grafik](https://user-images.githubusercontent.com/175809/29826811-981cab92-8cd8-11e7-9d3c-c910689edd74.png)
![grafik](https://user-images.githubusercontent.com/175809/29826827-a62d0038-8cd8-11e7-938f-c3478bcc2583.png)

**Comment by mre** [comment]
![grafik](https://user-images.githubusercontent.com/175809/29826885-ca90d2ec-8cd8-11e7-8a7d-40c70e226204.png)
![grafik](https://user-images.githubusercontent.com/175809/29826908-d8d60dfe-8cd8-11e7-9f00-976f8a7ab4ff.png)
